apiVersion: v1
kind: Template
metadata:
  name: cluster-create-template
objects:

- apiVersion: clusteroperator.openshift.io/v1alpha1
  kind: Cluster
  metadata:
    name: ${CLUSTER_NAME}
  spec:
    hardware:
      aws:
        accountSecret: 
          name: aws-credentials
        sshSecret:
          name: ssh-private-key
    machineSets:
    - name: master
      nodeType: Master
      infra: true
      size: 3
    - name: alpha
      nodeType: Compute
      size: 2
    - name: beta
      nodeType: Compute
      size: 5

parameters:
- name: CLUSTER_NAME
  displayName: Cluster Name
  description: The name to give to the Cluster created. If using real AWS, then this name should include your username so that resources created in AWS can be identified as yours.
  value: cluster1
  required: true
